// ABI v3: the syscall envelope, protobuf-encoded (CHALLENGE.md E, decided).
// The envelope stays uniform — one message shape for every capability, which
// is what keeps generic interposition (validate, journal, trace) possible —
// and the args/result payloads stay opaque JSON bytes.
//
// This file is the interop source of truth. The Go codec in this package is
// hand-rolled and reflection-free (TinyGo-safe, zero dependencies) and is
// verified against protoc-generated reference code in wire_interop_test.go;
// the Rust brain implements the same messages. Schema evolution rules are
// protobuf's: never reuse a field number, add fields freely — decoders skip
// what they do not know.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: envelope.proto

package refpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_RESULT      Status = 1
	Status_STATUS_YIELD       Status = 2
	Status_STATUS_FAILED      Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_RESULT",
		2: "STATUS_YIELD",
		3: "STATUS_FAILED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_RESULT":      1,
		"STATUS_YIELD":       2,
		"STATUS_FAILED":      3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

// Syscall is the guest-to-host request.
type Syscall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abi           uint32                 `protobuf:"varint,1,opt,name=abi,proto3" json:"abi,omitempty"`  // must equal 3
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // capability or reserved sys.* name
	Args          []byte                 `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"` // JSON payload, opaque to the envelope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Syscall) Reset() {
	*x = Syscall{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Syscall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Syscall) ProtoMessage() {}

func (x *Syscall) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Syscall.ProtoReflect.Descriptor instead.
func (*Syscall) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Syscall) GetAbi() uint32 {
	if x != nil {
		return x.Abi
	}
	return 0
}

func (x *Syscall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Syscall) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

// Response is the host-to-guest result.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abi           uint32                 `protobuf:"varint,1,opt,name=abi,proto3" json:"abi,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=aurora.sys.v3.Status" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`       // errno when status is STATUS_FAILED
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`   // JSON payload when status is STATUS_RESULT
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // human text on yield/failure
	Labels        []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`   // provenance of the result (sorted)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetAbi() uint32 {
	if x != nil {
		return x.Abi
	}
	return 0
}

func (x *Response) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Response) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Response) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\raurora.sys.v3\"C\n" +
	"\aSyscall\x12\x10\n" +
	"\x03abi\x18\x01 \x01(\rR\x03abi\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x03 \x01(\fR\x04args\"\xa9\x01\n" +
	"\bResponse\x12\x10\n" +
	"\x03abi\x18\x01 \x01(\rR\x03abi\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.aurora.sys.v3.StatusR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels*X\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_RESULT\x10\x01\x12\x10\n" +
	"\fSTATUS_YIELD\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03BAZ?github.com/aurora-capcompute/capcompute/sys/wire/internal/refpbb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envelope_proto_goTypes = []any{
	(Status)(0),      // 0: aurora.sys.v3.Status
	(*Syscall)(nil),  // 1: aurora.sys.v3.Syscall
	(*Response)(nil), // 2: aurora.sys.v3.Response
}
var file_envelope_proto_depIdxs = []int32{
	0, // 0: aurora.sys.v3.Response.status:type_name -> aurora.sys.v3.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
